[package]
name = "dtls"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version= "0.9.2", features = ["thread_rng"] }
rcgen = "0.14.6"
sha2 = "0.10.9"
tokio = { version = "1.49.0", features = ["full"] }
x25519-dalek = { version = "2.0.1", features = ["getrandom"] }
